# envs/dev/frontend-values.yaml

# Name + namespace
serviceName: fleet-frontend
namespace: fleet-dev

replicaCount: 1

image:
  repository: shemalperera/fleet-mgt-app-frontend
  tag: "1.0"
  pullPolicy: IfNotPresent  # or Always if you prefer

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  # ONLY works if you add nodePort support to service.yaml (see below)
  nodePort: 30050

# Turn off HPA logic so replicas: 1 is used
autoscaling:
  enabled: false

# Keep these empty if you don't care right now
env: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
ingress:
  enabled: false

healthCheck:
  enabled: false